version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-task-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://app:app@postgres:5432/app
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: fastapi-task-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
